qol updates - added version, log output, verbose option - now all processes are awaited before script closes.

diff --git a/gif-set b/gif-set
--- a/gif-set
+++ b/gif-set
@@ -1,21 +1,29 @@
 #!/usr/bin/bash
 
 NAME="gif-set"
+VERSION="1.0"
 
 USER_CONFIG="~/.config/$NAME.conf"
 LOCAL_CONFIG="./$NAME.conf"
 
 BATCH_DIR="./output"
 
+# pretty helpers
+info() { [ $VERBOSE ] && echo -e "\033[1;38m🫐  $1\033[0m"; }
+success() { echo -e "\033[1;32m🥝 $1\033[0m"; }
+error() { echo -e "\033[1;31m🍓 $1\033[0m"; }
+
 
 help() {
     cat << EOL 
+${NAME} ${VERSION}
 Basic tool to create gifs from a video file. Programmable via optional parameters, and user & local config files. Optional batch functionality.
     
-USAGE: ./gif-set [OPTIONS...] OUTPUT_PATH
+USAGE: ./${NAME} [OPTIONS...] OUTPUT_PATH
 
 ACTIONS
-    --help, -h : View this help menu.
+    --help, -h: View this help menu.
+    --verbose, -V: Print additional status updates.
 
 PARAMETERS:
     OUTPUT_PATH: Filepath for output. May be supplied by batch or config file.
@@ -31,7 +39,7 @@ BATCH OPTIONS:
     --batch, -b [PATH]: Path to CSV file with batch information. See README for more.
     --batch-index, -i [INDICES,...]: Pick-and-choose entries from the batch file by line number. Multiple are allowed, comma-separated. (Ignored if used without "--batch" flag.)
     
-For further information, view README.md.
+Crane Presents... ${NAME}, ${VERSION}
 EOL
     exit 0
 }
@@ -41,6 +49,7 @@ batch() {
     line_count=1
     mkdir -p "$BATCH_DIR"
 
+
     while IFS="," read -r name start length
     do
         if [ -z "$BATCH_INDICES" ] || [[ $(echo "$BATCH_INDICES" | grep -w "$line_count") ]]; then
@@ -48,6 +57,8 @@ batch() {
             START_TIME=$start
             DURATION=$length
             render &
+
+            pids+=($!)
         fi
 
         ((line_count++))
@@ -56,9 +67,18 @@ batch() {
 }
 
 render() {
-    echo "Rendering '$OUTPUT_PATH' ..."
+    info "Queueing render for '$OUTPUT_PATH' ..."
 
     ffmpeg -y -v quiet -ss "$START_TIME" -t "$DURATION" -i "$INPUT_FILE" -s "$DIMENSIONS" "$OUTPUT_PATH" &>/dev/null
+
+    pid+=("$!")
+
+    # log
+    if [ $? -eq 0 ]; then
+        success "Rendered '$OUTPUT_PATH' !"
+    else
+        error "RENDER NOT VALIDATED."    
+    fi
 }
 
 
@@ -67,6 +87,10 @@ while [[ $# -gt 0 ]]; do
     case $1 in
         -h|--help)
             help
+            ;;
+        -V|--verbose)
+            VERBOSE=true
+            shift
             ;;
         
         -I|--input)
@@ -126,10 +150,13 @@ done
 
 for conf in "$USER_CONFIG" "$LOCAL_CONFIG" "$CUSTOM_CONFIG"; do
     if [ -f "$conf" ]; then
-        echo "Using configuration from $conf ..."
+        info "Using configuration from $conf ..."
         source "$conf"
     fi
 done
+
+
+pids=()
 
 
 if [ "$BATCH_PATH" ]; then
@@ -137,9 +164,14 @@ if [ "$BATCH_PATH" ]; then
 else
     for i in START_TIME DURATION INPUT_FILE DIMENSIONS OUTPUT_PATH; do
         if [ -z ${!i} ]; then
-            echo "Parameter $i is missing!"
+            error "Parameter $i is missing!"
             exit 1
         fi
     done
     render
 fi
+
+# await all child processes
+for pid in ${pids[*]}; do
+    wait $pid
+done
